C++:
  indent_char: " "
  indent_size: 2
  max_line_length: 100
  space_before_function_paren: true
  space_after_function_paren: true
  space_before_block_open: true
  space_after_block_open: true
  space_before_block_close: true
  space_after_block_close: true
  space_before_conditional: true
  space_after_conditional: true
  space_before_operator: true
  space_after_operator: true
  use_tabs: false
  align_assignments: false
  align_parameters: false
  sort_imports: true
  include_guard: true
  brace_style: "allman"
  allow_single_line_blocks: true
CSS:
  indent_char: " "
  indent_size: 2
HTML:
  indent_char: " "
  indent_size: 2