name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          set -e
          npm install

      - name: Make Unibeautify executable
        run: chmod +x node_modules/.bin/unibeautify

      - name: Run Unibeautify
        run: npm run beautify